import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from './components/Sidebar';
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex mt-12"> {/* Adiciona margem no topo para o conteúdo não ficar sob o cabeçalho */}
          <Sidebar />
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
